### ISSUE TITLE
Low Latency

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/AdInsertion#10]
6.1.3.2.4: This doesn't take into account network latency.  if 2xMBT < 2xRTT, the client may not have enough time to request the content.  I agree that 2xMBT is a good lower bound for the request, but there are cases where the request should come even earlier.  Would it be better to also consider the MPD Validity Expiration must come at least 2 segments before the ad is to play or EPT whichever comes earlier?

**Comment by ZmGorynych** [comment]
Precise timing removed.
