### ISSUE TITLE
Mix of Events and xLinks

### ISSUE THREAD

**Issue by MillarKeith** [Dash-Industry-Forum/AdInsertion#12]
1.  It should be made clear that “Events” are automatically expired at the end of a Period. So for example you can’t use a mix of remote periods and “Events” within the same MPD for Ad insertion signalling. This is because the “Event” will no longer be valid once the Ad Period Starts and so in theory the device should ignore the “event”, and even if it was interpreted during the previous Period the events duration should be ignored once the Ad Period starts.

**Comment by alexgiladi** [comment]
Accepted

**Comment by ZmGorynych** [comment]
Sum of Event@presentationTime and Event@duration shall never exceed period duration
