### ISSUE TITLE
Remote Period shall return a Start Attribute

### ISSUE THREAD

**Issue by MillarKeith** [Dash-Industry-Forum/AdInsertion#13]
1.  Setting of the Start attribute within an Ad Period:  When using Remote Periods the data returned completely replaces the original MPD Period. This means that any “start” attribute is lost, and the remote server must include it within the data returned. It is difficult for a remote server to provide this information and so perhaps should be passed within the Remote Period request.

**Comment by ZmGorynych** [comment]
Accepted.
