### ISSUE TITLE
section 3.2.1.5 early termination

### ISSUE THREAD

**Issue by wendell74** [Dash-Industry-Forum/AdInsertion#14]
Early termination of an ad as outlined may work only in a few situations. This section talks about cutting short an ad to switch to breaking news. Ads may be pre-packaged and put on an Origin or Edge. So once the ad-insert system directs a client to an ad-manifest and ad-segments, any ‘emsg’ at the packager (in the main content) is not seen by the client until it comes back from the complete ad-break.
Even if the ad were being created in a Just-in-time fashion via a remote Period, the ad may be processed by a packager instance different from the packager processing the main content. So if the ad-break were to be interrupted the packager processing the ad has to be interrupted, this adds more complexity to the system.

**Comment by ZmGorynych** [comment]
We don't have a solution to this problem in the standard.

**Comment by ZmGorynych** [comment]
In general, you need to keep downloading event-bearing part of the period. 
In server-driven case shorter inserted periods can help avoiding the issue
This is easier done in app-driven case if the "main" presentation is continually downloaded despite not being played.
