### ISSUE TITLE
Allowing dIfferent segment duration for pre-packaged advertisements

### ISSUE THREAD

**Issue by mcntech** [Dash-Industry-Forum/AdInsertion#15]
Pre-packaged advertisements may have different segment duration compared to live content. The MPD attribute maxSegmentDuration  may be defined as  overridable by a similar attribute of period  element. This allows players to change the segment fetching algorithms suitably.

**Comment by ZmGorynych** [comment]
Standards changes should be addressed by MPEG. We will submit this as a part of DASH-IF input to the next meeting.

**Comment by ZmGorynych** [comment]
1. Use of this attribute is not recommended in case where all period characteristics are not known at MPD parse time. 
2. Ask MPEG for clarification and ask whether this can be done period-wise;
3. Put authoring constraints on changing (sub)segment length. In general, restrict cross-period changes in codecs etc.
4. Discuss buffering issues including this.
