### ISSUE TITLE
Allow for MPD-based ad signaling in app-driven, live workflow

### ISSUE THREAD

**Issue by kstreeter** [Dash-Industry-Forum/AdInsertion#16]
The current text of section 6.2.2 in v0.5 states that content must include an InbandEventStream containing events of type "urn:scte:scte35:2013:bin".  This is a valid interop point, but it is also common to signal these events directly in the MPD.  We should alter the text to require either inband or MPD based signaling.

**Comment by ZmGorynych** [comment]
Accepted. We can require either "urn:scte:scte35:2013:bin" inband, or "urn:scte:scte35:2013:xml" in MPD
