### ISSUE TITLE
Define the URI for Interop Points

### ISSUE THREAD

**Issue by irajs** [Dash-Industry-Forum/AdInsertion#17]
1- Interop URIs: addressed.
2- Reduce the number of interop points. 
3- A table summarizing the IOP list and the differences would help. 
4- We need to check also if we have an equivalent interop point for DVB DASH profile.
5- How does these interop points relate to DASH-IF IOP V2.0/3.0? How does the signalling works in MPD ? (need a section in intro to address this even if the IOPs are used in parallel).

**Comment by alexgiladi** [comment]
Will be addressed
