### ISSUE TITLE
Mandate in IF-3 the Event

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/AdInsertion#25]
Add a comment

**Comment by haudiobe** [comment]
addressed in latest version: https://1drv.ms/w/s!AiNJEPgowJnWgddH3qMKzknnTw9FBg

**Comment by technogeek00** [comment]
Agreed with Rufael as an additional update: For community review lets remove description of DASH Inband Event Messages as a possibility and only bring it back if significant concern is raised in community review.
