### ISSUE TITLE
Add a statement that IF-1 is conceptual

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/AdInsertion#26]

**Comment by haudiobe** [comment]
addressed in latest version: https://1drv.ms/w/s!AiNJEPgowJnWgddH3qMKzknnTw9FBg

**Comment by technogeek00** [comment]
I believe this was when IF-1 was the configuration to the encoder/packager, we've renamed this to IF-1' and described it as conceptual within 1.2.2 IF-1: Packager Ingest (second paragraph). ~Considering this resolved.~

**Comment by technogeek00** [comment]
Should we actually remove the IF-1' reference from the diagram? It looks like we never explicitly address what the form of said interface could be and it really has no effect on the architecture. I think the illustration of configuration being provided in the diagram and a comment on external configuration availability is enough for this.

**Comment by unifiedstreaming** [comment]
I think it still has value to keep this, as many exisiting deployments use this architectural distinction, it is NOT conceptual but a real interface affecting the majority of large scale streaming platforms today

**Comment by technogeek00** [comment]
We will ensure IF-1' is mentioned in IF-1, it is valuable to have the configuration called out.

**Comment by technogeek00** [comment]
Called out properly in latest draft
