### ISSUE TITLE
IF-1 Section needs correction

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/AdInsertion#27]

**Comment by technogeek00** [comment]
Can you elaborate here or point to an inline comment?

**Comment by unifiedstreaming** [comment]
This was discussed during one of the conference calls, progress was made, I still beleive more review of the discussion around the text of splice points is needed which was a recent addition to the text, especially the mapping to CMAF presenations and timeline origins

**Comment by technogeek00** [comment]
Agreed that the latest checks have gone over the texts thoroughly, we will open specific issues as needed.
