### ISSUE TITLE
addressing the use cases

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/AdInsertion#28]
in the current document use cases are only partially addressed

**Comment by technogeek00** [comment]
If you already have notes on the examples of cases not addressed can you describe them here? Quick glance it primarily looks to be the pre-roll live case, which we may want to move to not in scope of this document.

**Comment by haudiobe** [comment]
It would be good to add a note in the Ad Insertion CR in the use cases, which ones are addressed and which one not. I expect that MPEG will support work and we can update the document when the new use cases are addressed.

**Comment by unifiedstreaming** [comment]
in my opinion, live and recorded live are covered, vod is covered to some extent (albeit implicitly), i beleive the preroll to live and obfuscation are not covered. It may be beneficial for the industry to have a method for preroll into live, the obfuscation may be left out of scope or covered in a later stage. We could add this as notes, especially for these last two use cases MPEG may support.

**Comment by technogeek00** [comment]
Thomas has added Overview 1.1.1.1 to state we explicitly worked on LIVE and Transition issues, others will be expanded on overtime.
