### ISSUE TITLE
IF-4 Interface Clarification

### ISSUE THREAD

**Issue by technogeek00** [Dash-Industry-Forum/AdInsertion#31]
From Rufael:
> What about the interface itself? it is not so clear what the interface itself is, are there other options than VAST ? Please update this section making it a bit more clear what is recommended for the interface itself 

On the request side there appears to be no standard interface, but the responses are heavily standardized around VAST/VMAP. We can clarify the recommendation of VAST further as the response side, but should we also clarify there is no standard request structure?

**Comment by unifiedstreaming** [comment]
I think everyone would benefit from some text here, would it be beneficial to define request scheme in DASH-IF using VAST/VMAP?

**Comment by technogeek00** [comment]
Longer discussion captured missing clarity here: https://github.com/Dash-Industry-Forum/AdInsertion/issues/36

We will also provide recommendation of usage of VAST and specify additional options like SCTE-130

**Comment by technogeek00** [comment]
Finished in last revision.
