### ISSUE TITLE
IF-3 Metadata format paragraph

### ISSUE THREAD

**Issue by technogeek00** [Dash-Industry-Forum/AdInsertion#32]
On the paragraph:
> While the carriage method is considered normative, the format of the metadata is workflow dependent and is therefore out of the scope of this document. To carry metadata in one of the above mechanisms an event scheme should be defined by the workflow, optionally an existing scheme may be utilized. Informational examples of known schemes are provided in the subsequent sub-sections of this interface

From Rufael:
> remove this text it does not add anything

I added this text as part of our goal to explicitly call out normative and informational components of this spec. As the data format is not normative this seemed appropriate and frames the subsequent section. We could shift the statement of information only to the subsequent section, but I think it is important to have.

**Comment by unifiedstreaming** [comment]
no we need to be very clear and specific on the formatting requirements for interoperability, this text is too vague and should be removed. Especially we should recommend the schemes defined in SCTE 214 in order to avoid fragmentation in the industry

**Comment by technogeek00** [comment]
Remove exclusion of scope from the document, make listed examples recommendations

**Comment by technogeek00** [comment]
Updates accepted, additional examples can be provided via review
