### ISSUE TITLE
Mandate MPD Events in IF-6

### ISSUE THREAD

**Issue by technogeek00** [Dash-Industry-Forum/AdInsertion#33]
Similar to IF-3, should we mandate only the usage of MPD Events in IF-6?

**Comment by unifiedstreaming** [comment]
inband events may make sense to use for IF-6, as they can be understood by the player, but are harder to detect for ad blocking software,  i don't think that inband events have to be excluded, even though in some cases MPD events may make more sense.

**Comment by technogeek00** [comment]
Fair enough, lets keep
