### ISSUE TITLE
Formats for Ads

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/AdInsertion#36]
https://docs.google.com/document/d/1yxJh5F28F-JMVLyeDfolNtBKi1uvZsQb50m5rre3l_U/edit?usp=sharing

**Comment by technogeek00** [comment]
Through discussion on call it was identified we want to split the decisioning interface and the ad content format into separate interfaces. Decisioning interface will carry the information of the content format.

The content format needs definition, from call:
- Segments should be CMAF conforming
  - Make it a recommendation
  - Assume this is the case and leave non-CMAF content as needing detail checks from implementer
  - Same as main content
- Do we say more on how ads should be generated?
  - CMAF Fragment duration, bitrates
  - This is less important => experience from deployments already defines this
  - Low priority to address
- "Manifest"
  - MPD with single period
    - Following the CMAF profile that is defined in Amd. 1
    - Same as IF-2, but no splice points
  - Additional parameters to signal
    - Type is static
    - Duration is signaled in MPD

Main architecture diagram we will update to separate ad decisioning and conditioning systems. Separate IF-4 into IF-4 which is decisioning and IF-5 which is conditioning.

@haudiobe and @technogeek00 to collaborate on it

**Comment by technogeek00** [comment]
Section 1.2.6.2 created based on conversation, specified DASH-IF Ad Content format that contains format.

**Comment by technogeek00** [comment]
Note calling for additional restriction suggestions if the community would like them.
