### ISSUE TITLE
What are the mechanisms?

### ISSUE THREAD

**Issue by sandersaares** [Dash-Industry-Forum/AdInsertion#39]
The CR contains use case statements such as:

> While opportunities are generally expected to match the announced duration, in practice opportunities may be terminated early by the content author in response to the occurring event

Yet there is no obvious text that says how this is meant to be done. I would expect all statements in the use cases chapters to be backed up by some "mechanisms" chapter that defines how these decisions are made (e.g. how is content "terminated early", how this mechanism interacts with all the other mechanisms in DASH, etc). That might be followed by a description of the interfaces that make it possible to move the data that is required for these mechanisms to act (this seems to exist in the CR).

At the moment, there seems to be an entire "middle part" missing from the big picture and it is quite hard for me to understand the CR in a "user manual for someone wanting to use ads" sense. I would expect more than use cases and interfaces. I want to know "how things work", not just what APIs there are.

This is especially critical as some of the use cases are not easily solvable by any existing DASH mechanism that I am aware of (e.g. overwriting a non-predefined duration of live content). Defining the mechanisms might outline this and help prepare the additions to DASH (either in MPEG or DASH-IF scope) required to add the missing capabilities.

**Comment by haudiobe** [comment]
We made it clear that early termination is not yet addressed

**Comment by technogeek00** [comment]
We could more explicitly call this out in 1.1.1.1:

> This clause provides an overview of guiding use cases considered in the context of ad insertion for DASH. The initial focus is on _**Live Stream**_ use cases addressed in clause 1.1.1.3 together with the transition issues in clause 1.1.1.7.
> In future version of this document, the remaining use cases _**(VoD, Recorded Live, Pre-Roll into Live, and Advertisement Obfuscation**_) will be addressed. However, the tools documented in this clause may very well be used for ad insertion for all documented use cases.

Though I would suggest that we have covered VoD pretty thoroughly via the revisions, still we can formally consider it addressed in later revisions.
