### ISSUE TITLE
Conformance Requirements for DASH Events

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/AdInsertion#4]
1.2.3: Should the impact on the DASH player to expose these events be specified?  Otherwise, if these events are purely between the server and the DASH client, does it need to specified?  In the previous paragraph it was clear that the DASH client needed to support a timer.  It isn't clear what support is required here.

**Comment by ZmGorynych** [comment]
Clarified. We need to allow the application to register event-specific callbacks.
