### ISSUE TITLE
Numbered interfaces are hostile to reading comprehension

### ISSUE THREAD

**Issue by sandersaares** [Dash-Industry-Forum/AdInsertion#40]
As a reader unfamiliar to the document, all these IF-X numbers are meaningless to me. Give the interfaces names, please. "The inputs of IF-2 and IF-3" is only as meaningful as the word "Something" in my eyes. Whereas "The inputs from the Content Preparation interface and the Ad Avail Signaling interface" is far more understandable.

**Comment by haudiobe** [comment]
You need to look at the diagram and learn it. We may improve in the final one, but we should keep consistency

**Comment by haudiobe** [comment]
Two reasons:
- in editing it keeps more flexible
- scared of defining terms that may be more confusing
Ask community for names on the interface!

**Comment by technogeek00** [comment]
I'm up for getting names from the community, but we can also attempt to better qualify interface references when they are made in the text.

**Comment by RufaelDev** [comment]
Lets spend time on improving the document, in the end, what is in a name, ETSI and 3GPP also use such numbering for their interop points I don't really see the problem.
