### ISSUE TITLE
Gaps should not be tolerated

### ISSUE THREAD

**Issue by sandersaares** [Dash-Industry-Forum/AdInsertion#41]
The CR text says that gaps in the timeline can happen.

> Gaps or overlap of content on the master timeline: The content may not exactly be matching the envisaged insertion instructions and hence content may be overlapping at the splice points or there may be gaps. DASH permits signaling of such properties and playback platforms can handle the playback of content with such properties. 

This contradicts the timing model chapter in v5, which does not tolerate any gaps.

Ad insertion features of DASH should be designed to operate without any gaps anywhere, in any situation. A feature that leaves a gap needs to be redesigned.

**Comment by haudiobe** [comment]
The v5 timing model is good, but it does not mean that everyone always follows it. Gaps are a reality. So the sentence itself is not wrong.

**Comment by sandersaares** [comment]
> but it does not mean that everyone always follows it. Gaps are a reality

Yes, non-interoperable content exists in the world. We should not spend DASH-IF contributor time and energy nor the guidelines' readers time and energy on caring about services that are not designed to provide interoperable behavior.
