### ISSUE TITLE
Stream preconditioning for segment break points is unnecessary complexity

### ISSUE THREAD

**Issue by sandersaares** [Dash-Industry-Forum/AdInsertion#42]
The CR contains statements such as:

> If possible, content should be preconditioned such that segment boundaries are created at placement opportunities. 

I realize that only doing period switching at segment boundaries can be useful in increasing compatibility but a core principle of the proposed v5 timing model is that you can cut periods at any point, regardless of segment boundaries.

We should expect clients to implement this and provide good test vectors to assist client authors.

As such, I do not consider such preconditioning appropriate for ad insertion. Let's design a system that keeps the segmentation logic independent and the cross-cutting coordination requires in the packagers/encoders simple. Let the packager make segments based on the internal structure of a single (!) adaptation set (!).

Remember that audio and video need not be aligned anyway! Furthermore, examples were brought to the timing model discussion indicating very realistic cases where alignment was impossible in practice. Assuming aligned segment breaks is not a realistic scenario and puts unrealistic expectations on encoder/packager developers.

The v5 timing model sets the expectation that a DASH client can handle period transitions anywhere. Yes, some clients might have slight issues (e.g. unexpected time-shift during transitions) but these issues should be solved by fixing the client, not regressing our timing model expectations to an unrealistically simpler state.

Sure, the statement in the CR starts with "if possible" but that just adds ambiguity. Clients that can do seamless period transitions benefit not at all from this situation and clients that have special constraints for seamless period transitions need to be fixed. The price for any kind of segment boundary alignment across adaptation sets is far too high to ever be paid.

This also relates to the placement of I-frames at splice points (as seems to be assumed under IF-1) - while that's definitely nice and would help clients implement seamless period transitions with less effort, we should not assume this. Splice points can correspond to arbitrary samples or even occur in the middle of a sample. The client's job is to do the switching - we should not make assumptions about the sample structure for splice points. If I understood IF-1 chapter right (I find it hard to understand, so correct me if wrong), it says there have to be I-frames at splice points.

**Comment by haudiobe** [comment]
The latest version adds encoding option 3 to do so differently. It is still good to recommend that encoders so this, this aligns with CTA WAVE splice conditioning.

**Comment by haudiobe** [comment]
Add a clear question into the document to ask if they prefer one solution?

**Comment by sandersaares** [comment]
> Add a clear question into the document to ask if they prefer one solution?

My reading of the document was that it described different ways to precondition the stream. The fact that "don't precondition it" is an option is not obvious. So before any question can be raised, it needs to be worded much more clear.

Anyway, the experts in the ad insertion task force are the experts who have the knowledge to decide what is the right single interoperable way to do ad insertion. I would expect ad insertion task force to make this decision and take in community feedback to ensure that all the details are thought through and that the chosen solution is maximally interoperable. This does not mean every existing implementation has to be interoperable - interoperability is not some description of every option you can choose. We publish interoperability guidelines, not descriptions of things people do.

If ad insertion task force does not have the knowhow to make a well founded decision, why do we assume it has the understanding required to make an ad insertion chapter in the first place? Believe in me who believes in you!

**Comment by haudiobe** [comment]
We should make these two options
1) Stream Preconditioning
2) UNconditioned

**Comment by haudiobe** [comment]
addressed in version for community review
