### ISSUE TITLE
Minimum splice point advance notice time

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/AdInsertion#46]
Please provide feedback on:

"The minimum splice point advance notice time is known, i.e. the DASH packager gets a pre-notification or ad avail for a splice point that will be added to the media. This allows the DASH Packager to configure the minimum update period of the MPD properly. By this, the DASH client or MPD proxy requests the MPD in high enough frequency such that none of the announced Periods in the MPD are missed. For example, in SCTE-35, it is recommended to provide an advance notice of at least 4s [54]"

**Comment by RufaelDev** [comment]
4s was used in prior IOP v4.3, in many case MPD events will be available at the period start time which is much earlier than 4 seconds.

**Comment by technogeek00** [comment]
(2019/12/10) Detailed basics around value and referenced 4s from SCTE
