### ISSUE TITLE
Requirements and Restrictions for Ad Content

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/AdInsertion#48]
Ad Content is defined in clause 1.2.6.6. There are a set of restrictions and requirements. Please provide feedback if anything should be added, changed, etc.

**Comment by RufaelDev** [comment]
I like the proposed text, I would recommend being careful imposing to many things to be different as compared to the main content, as likely ad insertion preparation will use similar authoring tools as used for main content.

**Comment by acbegen** [comment]
I'd imagine in many cases, the ad content will actually be authored/encoded/packaged for the lowest common denominator in which case maybe those need to be stated clearly somewhere in our guidelines.

**Comment by technogeek00** [comment]
The following bullet is in the Ad Content section, do we feel this is enough to address @acbegen 's comment?
> -	The content may and typically should include multiple variants for the same ad, for example different codecs, formats and resolutions in order for the Dynamic Conditioning, the MPD proxy or a DASH client to adjust the ad to the current playback conditions.
