### ISSUE TITLE
Loudness/Volume constraints for transitions

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/AdInsertion#52]
loudness/volume of audio could perhaps be added , what would be constraints for loudness ?
A different loudness could really be annoying to users. 
what is the businessvalue of these use cases when codecs/tracks are changing compared to cloud transcoding ?
The sentence "However this can be handled at Period boundaries" what does this mean ?

**Comment by haudiobe** [comment]
(19/09/27 AdIn TF): Add this to CR

**Comment by RufaelDev** [comment]
I added a bullet, it may be good to add a note to the document and sollicit further input from audio experts or people working in this area.

**Comment by technogeek00** [comment]
This was fully implemented in the released document
