### ISSUE TITLE
Comment on 1.1.2

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/AdInsertion#53]
Architecture diagram should align with live and common industry practice, encryption typically happens at packager, as media encryption is not needed and may make many workflows more difficult to realize. Common encryption is only for usage at clients, server side you can use non media specific encryption available in transport and storage. Update packager in diagram to include encryption functionality.

**Comment by haudiobe** [comment]
(AdIn 19/09/27)
Agree to move encryption packager.
Create separate delivery box for segments for both ads as well as main content.

**Comment by technogeek00** [comment]
We have a secondary arrow but no box, did we still want to do that?

**Comment by RufaelDev** [comment]
It looks ok to me now

**Comment by technogeek00** [comment]
Addressed in published document https://dashif.org/docs/CR-Ad-Insertion-r8.pdf
