### ISSUE TITLE
Comments on section 1.1.3 Architectures

### ISSUE THREAD

**Issue by pgendron-harmonicinc** [Dash-Industry-Forum/AdInsertion#68]
The figure 1 provides an architecture overview for both SSAI and SGAI but this can create some complexity of understanding for people not mastering the two options .

- Some interfaces may be used only in the case of SGAI ( IF -7 and may be others).  Would that make sense to make this more explicit either in the section for each interface or in the drawing ?
- There are also different colors for the interfaces with no explanation of the meaning ( eg normative vs informative)
- As this drawing is key for the understanding of all the text in the next sections, I wonder if we could ease the reading for each section describing an interface, by copying a part of the architecture where the interface is located ( as it is done for example in section 1.2.7)
- we can still see a box called ''Dynamic ad Transcoding'' whereas it was said to be corrected to ''Dynamic Ad Preparation'' in #44

**Comment by haudiobe** [comment]
_Some interfaces may be used only in the case of SGAI (IF -7 and may be others). Would that make sense to make this more explicit either in the section for each interface or in the drawing ?_

As the document is written, it is correct. But you can use IF-7 also SSAI. So this should be documented more explicitly. (Zach)


_There are also different colors for the interfaces with no explanation of the meaning ( eg normative vs informative)_

Good point - colors are only art - no meaning. We should really check (Thomas).

_As this drawing is key for the understanding of all the text in the next sections, I wonder if we could ease the reading for each section describing an interface, by copying a part of the architecture where the interface is located ( as it is done for example in section 1.2.7)_

Good point  (Thomas)

_we can still see a box called ''Dynamic ad Transcoding'' whereas it was said to be corrected to ''Dynamic Ad Preparation'' in #44_

Thank you (Thomas)

**Comment by technogeek00** [comment]
Addressed in published document https://dashif.org/docs/CR-Ad-Insertion-r8.pdf
