### ISSUE TITLE
Comments on section 1.2.2 IF-1 : packager ingest

### ISSUE THREAD

**Issue by pgendron-harmonicinc** [Dash-Industry-Forum/AdInsertion#69]
in this section 3 options are described for the media at the splice points. Nothing is said here on the prevalence on such or such option. But on the section 1.2.4 (IF2-Content preparation) there is a sentence saying that alt least one media type ( generally video) should follow content conditioning according to Option1.
wouldn't be clearer to add a statement on section 1.2.2 saying that although option 1, 2 or 3 can be used by the different media, at least one should be formatted as option 1 ?

**Comment by haudiobe** [comment]
(2020/05/22): From IOPv5 this is carrying through. So we should make this part of the profile "good content option".

**Comment by technogeek00** [comment]
Addressed in published document https://dashif.org/docs/CR-Ad-Insertion-r8.pdf
