### ISSUE TITLE
Comments on section 1.2.6 IF-4 Ad Decisionning and Exchange Interfaces

### ISSUE THREAD

**Issue by pgendron-harmonicinc** [Dash-Industry-Forum/AdInsertion#70]
The breakdown into several IF-4x interfaces with different purpose is interesting and should clarify the global workflows but it might need a bit more description of the processes involved when the Proxy initiate the call. 

- May be in the Introduction section and before going into the details for each interfaces in the subsequents sections that would be  good to have either a text or a drawing that shows the information flow from IF-4a to the other. 

- Depending on wether this is a SSAI or SGAI workflow this information flow is different. The reader can understand this after a careful reading of, for example section 1.2.6.2.2 but this could be made more explicit thought a drawing.

- As an example, from the reading of the description of each IF-4x, I don't see how and if  the Ad Decision Server answer is going back to the Proxy

**Comment by haudiobe** [comment]
(2020/05/22): Put a box around all IF-4. 2 inputs/1 output. Describe this in intro.

**Comment by haudiobe** [comment]
(IOP 20/5/29) Zach's part resolved

**Comment by technogeek00** [comment]
https://dashif.org/docs/CR-Ad-Insertion-r8.pdf
