### ISSUE TITLE
comments on section 1.2.6.2 IF-4a  Ad decision request parameters

### ISSUE THREAD

**Issue by pgendron-harmonicinc** [Dash-Industry-Forum/AdInsertion#71]
This interface seems to be described as a unidir interface as the answers from the Ad decision servers seems to go to the Ad Content server through IF-4e. Is that true ? there is no feedback to the Proxy ??

In that case the description of IF-6 -Ad metadata says : 
> Ad metadata, such as creative descriptions, viewability requirements, and tracking events, is provided to the Ad Insertion MPD Manipulator as part of the IF-4 ad decisioning response.
>
needs to be clarified

**Comment by haudiobe** [comment]
merged with #70
