### ISSUE TITLE
Comments on section 1.2.6.3 IF-4b content conditionning request parameters

### ISSUE THREAD

**Issue by pgendron-harmonicinc** [Dash-Industry-Forum/AdInsertion#72]
Should we replace ''Ad content Server'' by ''Dynamic Ad Preparation'' in the following ? 

> A conditioning parameter is a piece of information about the encoding/packaging of the content stream or a client player capability that is used by the Ad Content Server to ensure an ad creative is compatibly encoded for inclusion in the generated presentation. The Ad Insertion MPD Manipulator collects and sends this information to the Ad Content Server as part of IF-4b.
>

**Comment by haudiobe** [comment]
(2020/05/22): Does not have to transcode, but it is an option. Diagram is correct. No changes needed. Make sure that the text is explaining that transcoding is an option.

**Comment by haudiobe** [comment]
(IOP 20/5/29) Thank you Zach
