### ISSUE TITLE
comment on section 1.2.6.5 IF-4e Ad Selection Result format

### ISSUE THREAD

**Issue by pgendron-harmonicinc** [Dash-Industry-Forum/AdInsertion#73]
Seems strange to me that the the ADS answer goes only to the Ad content server and not back to the proxy, but i am not an ad insertion expert ;-)

Last sentence of 1.2.6.5.1 says 
> For the purposes of this document we will assume VAST is used
> 
but in the following sections  VAST and SCTE130 are presented as two possible alternative.

Should we be a bit more prescriptive saying that Vast is the preferred option for DASH-IF because giving too many options, even if this corresponds to some real existing deployment will make things harder for interoperability.

I'd like a sentence like ''DASH-IF recommend the use of VAST version xx ( 4.1?)'' for reason x, y, z.

If usages of VAST  vs SCTE130 can be linked to some type of environment or regional usage, can we mentioned that in order to instruct the decision of someone wondering if VAST or SCTE130 is the best fit for him ?

**Comment by haudiobe** [comment]
(2020/05/22): We do not even have to assume VAST, does not provide benefit. Better provide what the functionality is that need and say how VAST and SCTE130 provide the functionality as an example. We say that we assume that this functionality is available (and we can write this as MUST for an external system).

**Comment by haudiobe** [comment]
(IOP 20/5/29) Thank you Zach
