### ISSUE TITLE
Comments on section 1.2.6.6 IF-4d : DASH-F Ad Content Storage format

### ISSUE THREAD

**Issue by pgendron-harmonicinc** [Dash-Industry-Forum/AdInsertion#74]
This interface describes a DASH formatted content that should go through the Dynamic Ad Processing box before going to the proxy through the IF-4C. But If my understanding is correct there is no mention of the possibility that the Ad Content can be available only on a mezzanine format or generally not at the right format/codec and should therefore be transcoded/processed in the next box.
This may be due to the fact that the document describes in length the interface but not much the function being executed in the boxes.

**Comment by haudiobe** [comment]
(2020/05/22): Ok, add this description.

**Comment by technogeek00** [comment]
In published document https://dashif.org/docs/CR-Ad-Insertion-r8.pdf
