### ISSUE TITLE
Comments on section 1.2.6.7 IF-4c

### ISSUE THREAD

**Issue by pgendron-harmonicinc** [Dash-Industry-Forum/AdInsertion#75]
reading the description of the interface, it looks like the Dynamic Ad content delivered by the Dynamic Ad processor is a filtered version of the Ad Content (IF-4d). There is no mention that the Ad content could be transcoded 'on the fly'' in the Processor box. See also comment on IF-4d #74

**Comment by haudiobe** [comment]
merged with #74
