### ISSUE TITLE
Comments on section 1.2.7.1 - IF-5 overview

### ISSUE THREAD

**Issue by pgendron-harmonicinc** [Dash-Industry-Forum/AdInsertion#76]
There might be some typo here ::

> 2) The ad content on IF-4b follows the DASH Ad insertion content as defined in clause 1.2.6.6. In addition, the content may be conditioned, for example such that for any Initialization/Adaptation Set present in the MPD on IF-2, at least one Adaptation Set is provided in the ad content on IF-4b.

> 3) The ad content on IF-4b has at least the duration ADDU, but may be marginally longer. If longer, then it is expected that the content can be cut at the end.

> 

Dynamic Ad content is described in interface IF-4c / in section 1.2.6.7, and in interface IF-4d / in section 1.2.6.6 but not in IF-4b (conditioning parameters)

**Comment by technogeek00** [comment]
Numbering was rearranged without all text updates, needs fix.

**Comment by haudiobe** [comment]
(IOP 20/5/29) Thank you Zach
