### ISSUE TITLE
Comment on section 1.2.8 IF-6 Ad metadata signaling

### ISSUE THREAD

**Issue by pgendron-harmonicinc** [Dash-Industry-Forum/AdInsertion#77]
in the introduction, the following sentence 

> Ad metadata, such as creative descriptions, viewability requirements, and tracking events, is provided to the Ad Insertion MPD Manipulator as part of the IF-4 ad decisioning response.

> 
makes me think that the proxy receives an answer from the Ad decision Server through interface IF-4a that should then be bidirectional , although this is not so clear. Can you clarify this ?

**Comment by technogeek00** [comment]
Hmm the directionality of flow in the ad interfaces dont directly follow the practical implementation, more discussion needed on call.

**Comment by haudiobe** [comment]
(2020/05/22): Agreed, improve description,

**Comment by haudiobe** [comment]
(IOP 20/5/29) Thank you Zach
