### ISSUE TITLE
Comment on section 1.2.10 IF-8 Ad tracking and measurement

### ISSUE THREAD

**Issue by pgendron-harmonicinc** [Dash-Industry-Forum/AdInsertion#79]
There is some ambiguity in the introduction of this section where it is written that ad tracking and measurement integration is workflow dependent and therefore out of the scope of the document, but still some mechanism are briefly presented. 
Should DASH-IF express some recommendation on possibly ''better''/more future proof  solution between 1.2.10.2 and 1.2.10.3?

**Comment by technogeek00** [comment]
We actually reached out to IAB to clarify this point as it was previously VAST/VMAP, their feedback was to remove VMAP and include Open Measurement, these specifications would not be mutually exclusive and could be used going forward. IAB is considering further description of Open Measurement in DASH, but the details are left to them to solve.

**Comment by haudiobe** [comment]
(IOP 20/5/29) No actions in the document - are we good to close? If no comments until next call we will do so
