### ISSUE TITLE
recommend usage of EventStream@presentationTimeOffset for SCTE-214

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/AdInsertion#80]
As scte events typically continue across the entire presentation, we should recommend the use of EventStream@presentationTimeOffset, this allows scte information to be re-signalled in the ad-period or scte events starting in a previous period or future period,  this can be supported today, is consistent with the media.

**Comment by technogeek00** [comment]
The guidelines as written actually expect the usage of this based on suggested mapping of SCTE to EventStream, need to provide entry in table and minor description as part of Period creation at splice points and event stream copying for insertion of ads.

**Comment by technogeek00** [comment]
Thanks to @haudiobe for implementation

**Comment by technogeek00** [comment]
Closed implementation in 2020/10/02 call
