### ISSUE TITLE
Remove InitializationSet requirement

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/AdInsertion#81]
I recommend to remove any requirement for initialization set as it does not make much sense
 
- no one uses this 
- you cannot initialize multiple decoder pipes for the same stream anyways
- you dont know in advance anyway what initialization segs will be needed
- there is no need to introduce state between periods/manifest hampering ad insertion workflows

**Comment by technogeek00** [comment]
From 9/18 Call:
- InitializationSet utility not apparent in document
- Clarification that proxy can utilize to better condition and that clients or streams without ad insertion do not need to utilize these functionalities
- Potential of a "minimal initialization set" that could be described, need to check details on functionality

Note: 5.3.12 MPEG 23009-1 4th Edition

**Comment by technogeek00** [comment]
Closed implementation in 2020/10/02 call
