### ISSUE TITLE
IF-6 VAST Signalling Method

### ISSUE THREAD

**Issue by technogeek00** [Dash-Industry-Forum/AdInsertion#82]
The `https://dashif.org/identifiers/vast30` scheme, defined in DASH IOP v4.3 Section 5.3.3.7, describes the carriage of an entire VAST response as part of a single Event element which can then be picked up by a library within the application client that parses out and handles the eventing.

As part of the Ad Insertion CR we do not carry through the recommendation of full payload insertion, instead describing the breakdown of a VAST document into tracking events as part of IF-8 where we describe how a VAST tracking event can be mapped to timed presentation events. This description was added as a result of the feedback in #30, but we did not provide a scheme after the follow-up #59 issue was discussed as we felt this was more of a responsibility of the IAB group as they own the VAST specification.

When the parity check between v4.3 and the CR was done as part of #62, the discussion at the F2F in December 2019 agreed that the coverage of VAST was accurate with our desired approach.

Open questions from 2020/10/16 call:
- Should we bring back usage of previous scheme for backwards compatibility?
- Should we define a new scheme for the event breakdown callout since we did not get uptake from IAB on a definition?

**Comment by technogeek00** [comment]
fyi @haudiobe @RufaelDev

**Comment by haudiobe** [comment]
If no comment is received by Nov 9, 2020 call, we leave this as is.

**Comment by RufaelDev** [comment]
Some comments/observations:

1. In general adding VAST is not easy as URL's tend to expire quickly 
2. Defining something else to do reporting with a custom scheme makes some sense 
3. we are not really using this at the moment, are we sure others are not using this
4. Is DASH-IF ok that other third parties will define these URL's that imply certain player behavior to do the reporting, i.e. no 
   reporting in native player except for callback events

So ok leaving it as is is possible, it still may be helpful to inform the reader in some way as this 
does indeed remove a "feature" from the previous iop version

**Comment by haudiobe** [comment]
IOP TF 2020/11/06:
* We add a note to the updated version indicating that we removed a feature from previous iop version
* Issue will be closed to keep track of the discussion
